2025/03/24 09:10 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_article_vs_title_polarity: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_subject: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_source: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_article_vs_title_characters: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_media: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:Failed to import sl_visualisations.visualisations.plot_hex_charcounts: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:10 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_article_vs_title_polarity: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_subject: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_source: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_article_vs_title_characters: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_article_count_by_media: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:Failed to import sl_visualisations.visualisations.plot_hex_charcounts: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:11 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations'
2025/03/24 09:13 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 09:15 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 09:19 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:19 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:41 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:41 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:53 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:53 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:55 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:55 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'ML_model.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model.pkl'
2025/03/24 09:57 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'ML_model_regression.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model_regression.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model_regression.pkl'
2025/03/24 09:57 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'ML_model_regression.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 12, in load_model
    model = joblib.load("ML_model_regression.pkl")  # Replace with your actual model path
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ML_model_regression.pkl'
2025/03/24 10:00 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'vectorizer.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 13, in load_model
    vectorizer = joblib.load("vectorizer.pkl")  # Load the text vectorizer
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'vectorizer.pkl'
2025/03/24 10:00 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'vectorizer.pkl'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 16, in <module>
    model, vectorizer = load_model()
                        ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 217, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 242, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\caching\cache_utils.py", line 299, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 13, in load_model
    vectorizer = joblib.load("vectorizer.pkl")  # Load the text vectorizer
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\joblib\numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'vectorizer.pkl'
2025/03/24 10:19 ERROR:Error in pagesetup: [Errno 2] No such file or directory: 'sl_data_for_dashboard//evaluation_metrics.csv'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 38, in <module>
    evaluation_metrics = pd.read_csv("sl_data_for_dashboard//evaluation_metrics.csv")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sl_data_for_dashboard//evaluation_metrics.csv'
2025/03/24 10:19 CRITICAL:Menu setup crashed: [Errno 2] No such file or directory: 'sl_data_for_dashboard//evaluation_metrics.csv'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
  File "H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py", line 38, in <module>
    evaluation_metrics = pd.read_csv("sl_data_for_dashboard//evaluation_metrics.csv")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sl_data_for_dashboard//evaluation_metrics.csv'
2025/03/24 10:33 ERROR:Error in pagesetup: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
ImportError: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
2025/03/24 10:33 ERROR:Error in pagesetup: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
ImportError: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
2025/03/24 10:33 CRITICAL:Menu setup crashed: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
ImportError: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
2025/03/24 10:33 CRITICAL:Menu setup crashed: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
ImportError: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
2025/03/24 10:36 CRITICAL:Menu setup crashed: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 68, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 12, in pagesetup
    from sl_app_pages.ML_page import load_model as machinelearning
ImportError: cannot import name 'load_model' from 'sl_app_pages.ML_page' (H:\VScode\real-or-dubious-main\sl_app_pages\ML_page.py)
2025/03/24 11:40 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 11:44 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 11:46 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 02:59 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 08:22 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 08:31 ERROR:JSON Decode Error: Extra data: line 81 column 4 (char 12774)
2025/03/24 08:37 ERROR:JSON Decode Error: Extra data: line 81 column 4 (char 12774)
2025/03/24 10:15 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 10:19 ERROR:Failed to import sl_visualisations.subjectivity_refactor.plot_polarity_contrad_variations: module 'sl_visualisations.subjectivity_refactor' has no attribute 'plot_polarity_contrad_variations'
2025/03/24 10:19 ERROR:Failed to import sl_visualisations.subjectivity_refactor.plot_polarity_contrad_variations: module 'sl_visualisations.subjectivity_refactor' has no attribute 'plot_polarity_contrad_variations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:Function `plot_article_vs_title_subjectivity` not found in `sl_visualisations.other_visuals_refactor`.
2025/03/24 10:19 ERROR:Function `plot_article_vs_title_subjectivity` not found in `sl_visualisations.other_visuals_refactor`.
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:ImportError: Could not load `sl_visualisations.visualisations`. Error: No module named 'sl_visualisations.visualisations'
2025/03/24 10:19 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:19 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:25 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:25 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:27 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 10:27 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 10:33 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:52 ERROR:JSON Decode Error: Expecting ',' delimiter: line 385 column 1 (char 27417)
2025/03/24 10:56 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 10:56 ERROR:Error in plot_wordcloud_all: 'text'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\pandas\core\indexes\base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\wordcloud_visuals.py", line 22, in plot_wordcloud_all
    all_text = get_cleaned_text(df)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\common_visual_functions.py", line 204, in get_cleaned_text
    return " ".join(df["text"].astype(str).str.lower().str.split().sum())
  File "H:\python310\lib\site-packages\pandas\core\frame.py", line 3896, in __getitem__
    indexer = self.columns.get_loc(key)
  File "H:\python310\lib\site-packages\pandas\core\indexes\base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_all`: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_false`: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_true`: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_common`: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_dubious`: 'text'
2025/03/24 10:56 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_ngram_comparison`: 'text'
2025/03/24 11:04 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_day_label`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_day_label`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_day`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_day`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_location`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.article_count_refactor.plot_article_count_by_location`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_false`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_false`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_true`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_true`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_common`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_common`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_dubious`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_dubious`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_ngram_comparison`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:25 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_ngram_comparison`: expected ':' (common_visual_functions.py, line 24)
2025/03/24 11:26 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 11:28 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 11:33 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 11:33 ERROR:Error in plot_wordcloud_all: 'NoneType' object has no attribute 'from_csv'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_visualisations\wordcloud_visuals.py", line 18, in plot_wordcloud_all
    df = get_dataset_or_error(dataflag="text")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_visualisations\common_visual_functions.py", line 23, in get_dataset_or_error
    df= df.from_csv("sl_data_for_dashboard//preprocessed_wordcloud.zip")
        ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'from_csv'
2025/03/24 11:33 ERROR:Function `plot_wordcloud_all` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:33 ERROR:Function `plot_wordcloud_false` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:33 ERROR:Function `plot_wordcloud_true` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:33 ERROR:Function `plot_wordcloud_common` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:33 ERROR:Function `plot_wordcloud_dubious` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:33 ERROR:Function `plot_ngram_comparison` not found in `sl_visualisations.wordcloud_visuals`.
2025/03/24 11:46 CRITICAL:First load crashed: [Errno 2] No such file or directory: 'sl_data_for_dashboard//preprocessed_wordcount.zip'
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 62, in <module>
    st.session_state['wordcount_data'] = load_wordcount_data()
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 58, in load_wordcount_data
    return wordcountdata()
           ^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\f_dashboard\data_prep.py", line 201, in wordcountdata
    df = pd.read_csv(
         ^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\common.py", line 784, in get_handle
    handle = _BytesZipFile(
             ^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\io\common.py", line 1027, in __init__
    self.buffer: zipfile.ZipFile = zipfile.ZipFile(  # type: ignore[assignment]
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgold\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1323, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sl_data_for_dashboard//preprocessed_wordcount.zip'
2025/03/24 11:48 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/24 11:48 ERROR:Error in plot_wordcloud_all: 'title'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'title'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_visualisations\wordcloud_visuals.py", line 22, in plot_wordcloud_all
    all_text = get_cleaned_text(df)
               ^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_visualisations\common_visual_functions.py", line 216, in get_cleaned_text
    return " ".join(df["title"].astype(str).str.lower().str.split().sum())
                    ~~^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\core\frame.py", line 3896, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_all`: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_false`: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_true`: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_common`: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_wordcloud_dubious`: 'title'
2025/03/24 11:48 ERROR:Execution error for `sl_visualisations.wordcloud_visuals.plot_ngram_comparison`: 'title'
2025/03/24 11:49 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/24 11:50 ERROR:Failed to import sl_visualisations.wordcloud_visuals.plot_ngam_comparison: module 'sl_visualisations.wordcloud_visuals' has no attribute 'plot_ngam_comparison'
2025/03/25 08:39 ERROR:JSON Decode Error: Expecting ':' delimiter: line 77 column 9 (char 15125)
2025/03/25 08:41 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 08:48 ERROR:JSON Decode Error: Extra data: line 81 column 4 (char 14592)
2025/03/25 08:48 ERROR:JSON Decode Error: Extra data: line 81 column 4 (char 14592)
2025/03/25 08:48 ERROR:JSON Decode Error: Extra data: line 81 column 4 (char 14592)
2025/03/25 08:49 ERROR:Error in execute_element_call: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 08:49 ERROR:Error in execute_element_call: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 08:49 ERROR:Error in execute_element_call: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 08:49 CRITICAL:Menu setup crashed: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 08:49 CRITICAL:Menu setup crashed: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 08:49 CRITICAL:Menu setup crashed: Error opening 'wordcloud//wordcloud_all.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordcloud//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 94, in execute_element_call
    st.image(content, use_column_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordcloud//wordcloud_all.png'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:01 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/25 09:04 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_common.png'
Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
         ^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_common.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 72, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
    ^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
    ^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 165, in display_page
    execute_element_call(tab_contents.get("tab2",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
                    ^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h:\VScode\real-or-dubious-main\.venv\Lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_common.png'
2025/03/26 09:42 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/26 09:43 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
2025/03/26 09:43 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
2025/03/26 09:44 CRITICAL:Menu setup crashed: Can only use .dt accessor with datetimelike values
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 20, in display_maps
    articles["date"] = articles["date"].dt.date
  File "H:\python310\lib\site-packages\pandas\core\generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
  File "H:\python310\lib\site-packages\pandas\core\accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "H:\python310\lib\site-packages\pandas\core\indexes\accessors.py", line 608, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
2025/03/26 09:46 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:46 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:46 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:46 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:47 ERROR:Error in notesondataprep_body: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:47 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:47 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/26 09:47 ERROR:Error in notesondataprep_body: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:47 CRITICAL:Menu setup crashed: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\notesondataprep.py", line 7, in notesondataprep_body
    tab1, tab2, tab3 = st.tabs("Source Data",
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
TypeError: LayoutsMixin.tabs() takes 2 positional arguments but 4 were given
2025/03/26 09:58 ERROR:Error in pagesetup: invalid syntax. Perhaps you forgot a comma? (map_visualisation.py, line 202)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 13, in pagesetup
    from sl_app_pages.mod_page_calls import (
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 7, in <module>
    from sl_visualisations.map_visualisation import display_maps
  File "H:\VScode\real-or-dubious-main\sl_visualisations\__init__.py", line 15, in <module>
    module = importlib.import_module(f"{__name__}.{module_name}")
  File "H:\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 202
    y=0.5
      ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
2025/03/26 09:58 CRITICAL:Menu setup crashed: invalid syntax. Perhaps you forgot a comma? (map_visualisation.py, line 202)
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 13, in pagesetup
    from sl_app_pages.mod_page_calls import (
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 7, in <module>
    from sl_visualisations.map_visualisation import display_maps
  File "H:\VScode\real-or-dubious-main\sl_visualisations\__init__.py", line 15, in <module>
    module = importlib.import_module(f"{__name__}.{module_name}")
  File "H:\python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 202
    y=0.5
      ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
2025/03/26 10:05 ERROR:Error in display_maps: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
    title_text=(f'Article Mentions ({geo_level} level)'
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:05 ERROR:Error in display_maps: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
    title_text=(f'Article Mentions ({geo_level} level)'
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:05 CRITICAL:Menu setup crashed: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
    title_text=(f'Article Mentions ({geo_level} level)'
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:05 CRITICAL:Menu setup crashed: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
    title_text=(f'Article Mentions ({geo_level} level)'
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:06 CRITICAL:Menu setup crashed: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:06 CRITICAL:Menu setup crashed: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:06 CRITICAL:Menu setup crashed: local variable 'geo_level' referenced before assignment
Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 75, in interactive_map
    display_maps()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_visualisations\map_visualisation.py", line 45, in display_maps
UnboundLocalError: local variable 'geo_level' referenced before assignment
2025/03/26 10:10 ERROR:Failed to import Nothing.nothing: No module named 'Nothing'
2025/03/26 11:08 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
2025/03/26 11:08 ERROR:Error in execute_element_call: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
2025/03/26 11:08 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
2025/03/26 11:08 CRITICAL:Menu setup crashed: Error opening 'wordclouds//wordcloud_all.png'
Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 427, in image_to_url
    with open(image, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 164, in _read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wordclouds//wordcloud_all.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\VScode\real-or-dubious-main\Real_Or_Dubious_News.py", line 81, in <module>
    ROD_menu.pagesetup()
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\ROD_menu.py", line 40, in pagesetup
    app.run()  # Run the  app
  File "H:\VScode\real-or-dubious-main\sl_app_pages\multi_page.py", line 43, in run
    page["function"]()  # Run the selected page's function
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\mod_page_calls.py", line 70, in mp4_datapre
    display_page("Word Data Analysis")
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\modular_page.py", line 119, in display_page
    execute_element_call(tab_contents.get("tab1",
  File "H:\VScode\real-or-dubious-main\sl_utils\logger.py", line 64, in wrapper
    result = func(*args, **kwargs)
  File "H:\VScode\real-or-dubious-main\sl_app_pages\page_configs.py", line 95, in execute_element_call
    st.image(content, use_container_width=True)
  File "H:\python310\lib\site-packages\streamlit\runtime\metrics_util.py", line 409, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 204, in image
    marshall_images(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 588, in marshall_images
    proto_img.url = image_to_url(
  File "H:\python310\lib\site-packages\streamlit\elements\image.py", line 439, in image_to_url
    url = runtime.get_instance().media_file_mgr.add(image, mimetype, image_id)
  File "H:\python310\lib\site-packages\streamlit\runtime\media_file_manager.py", line 226, in add
    file_id = self._storage.load_and_get_id(
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 115, in load_and_get_id
    file_data = self._read_file(path_or_data)
  File "H:\python310\lib\site-packages\streamlit\runtime\memory_media_file_storage.py", line 167, in _read_file
    raise MediaFileStorageError(f"Error opening '{filename}'") from ex
streamlit.runtime.media_file_storage.MediaFileStorageError: Error opening 'wordclouds//wordcloud_all.png'
